create table if not exists public.okeechobee_helpers (
  id uuid primary key default gen_random_uuid(),

  name text not null,
  email text not null,
  phone text not null,

  categories text[] not null default '{}',
  area text,
  availability text,

  notifications_enabled boolean not null default true,
  active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint okeechobee_helpers_email_unique unique (email)
);

alter table public.okeechobee_helpers
  enable row level security;


create table if not exists public.okeechobee_helper_matches (
  id bigint generated by default as identity primary key,

  helper_id uuid not null
    references public.okeechobee_helpers(id)
    on delete cascade,

  project_slug text not null,

  join_token_hash text not null unique,

  joined_at timestamptz,
  notified_at timestamptz,

  created_at timestamptz not null default now(),

  constraint okeechobee_helper_match_unique
    unique (helper_id, project_slug)
);

alter table public.okeechobee_helper_matches
  enable row level security;

comment on table public.okeechobee_helpers is
  'Private reusable helper profiles for Okeechobee Together matching and notifications.';

comment on table public.okeechobee_helper_matches is
  'Private secure helper-to-project invitations. Raw invitation tokens are never stored.';
