create table if not exists public.okeechobee_project_owners (
  id bigint generated by default as identity primary key,

  project_slug text not null unique,

  resident_name text not null,
  resident_email text,
  resident_phone text,

  manage_token_hash text not null unique,

  approval_email_sent_at timestamptz,
  last_notification_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.okeechobee_project_owners
  enable row level security;

comment on table public.okeechobee_project_owners is
  'Private ownership records for Okeechobee Together community projects. Accessed only through protected server-side workflows.';

comment on column public.okeechobee_project_owners.manage_token_hash is
  'SHA-256 hash of the private resident management token. Raw token is never stored.';
